"""Add models

Revision ID: 6d442f482e44
Revises: 5711b2310cba
Create Date: 2023-08-30 12:45:18.486197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d442f482e44'
down_revision: Union[str, None] = '5711b2310cba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('makers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('maker', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('maker')
    )
    op.create_table('models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('engine', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('maker_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['maker_id'], ['makers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('models')
    op.drop_table('makers')
    # ### end Alembic commands ###
